import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { services, serviceBySlug, serviceProcess } from "@/content/services";
import { Accordion } from "@/components/ui/Accordion";
import { Button } from "@/components/ui/Button";
import { JsonLd } from "@/components/seo/JsonLd";
import { site } from "@/content/site";

export function generateStaticParams(){return services.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const service=serviceBySlug(slug);if(!service)return{};return{title:service.metadata.title.replace(" | DG Team",""),description:service.metadata.description,alternates:{canonical:`/leistungen/${slug}`},openGraph:{title:service.metadata.title,description:service.metadata.description}}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=serviceBySlug(slug);if(!service)notFound();const related=services.filter(item=>item.slug!==slug).slice(0,3);const jsonLd={"@context":"https://schema.org","@type":"Service",name:service.title,description:service.description,provider:{"@type":"ProfessionalService",name:site.name,url:site.url},areaServed:{"@type":"Country",name:"Deutschland"}};const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Startseite",item:site.url},{"@type":"ListItem",position:2,name:"Leistungen",item:`${site.url}/leistungen`},{"@type":"ListItem",position:3,name:service.title,item:`${site.url}/leistungen/${service.slug}`}]};const faqJsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:service.faqs.map(faq=>({"@type":"Question",name:faq.question,acceptedAnswer:{"@type":"Answer",text:faq.answer}}))};return <><JsonLd data={jsonLd}/><JsonLd data={breadcrumbJsonLd}/><JsonLd data={faqJsonLd}/><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Startseite</Link><span>/</span><Link href="/leistungen">Leistungen</Link><span>/</span><span>{service.shortTitle}</span></div><span className="service-no" style={{display:'block',marginTop:'3rem'}}>{service.number} / 05</span><h1>{service.title}</h1><p className="lead">{service.description}</p><div className="trust-points">{service.trust.map(point=><span className="tag" key={point}>{point}</span>)}</div><div className="hero-actions"><Button href={`/angebot?leistung=${service.slug}`}>Angebot anfragen</Button><Button href="/kontakt" variant="secondary">Direkt abstimmen</Button></div></div></section>
  <section className="section"><div className="container split-grid"><div><span className="eyebrow">Leistungsumfang</span><h2 className="display">Klar definiert. Passend zum Projekt.</h2></div><div>{service.limitation&&<div className="notice" style={{marginBottom:'2rem'}}>{service.limitation}</div>}<div className="audience-list">{service.scope.map(item=><div className="audience" key={item}><CheckCircle2 className="red" size={20}/><strong>{item}</strong></div>)}</div></div></div></section>
  <section className="section" style={{background:'#0d0d0d'}}><div className="container split-grid"><div><span className="eyebrow">Geeignet für</span><h2 className="display">Situationen und Flächen.</h2></div><div className="state-cloud">{service.audiences.map(item=><span className="tag" key={item}>{item}</span>)}</div></div></section>
  <section className="section"><div className="container split-grid"><div><span className="eyebrow">Ablauf</span><h2 className="display">Von der Anfrage zur Übergabe.</h2></div><div className="timeline">{serviceProcess.map((step)=><div className="step" key={step.no}><span className="service-no">{step.no}</span><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></div></section>
  <section className="section" style={{background:'#0d0d0d'}}><div className="container split-grid"><div><span className="eyebrow">Häufige Fragen</span><h2 className="display">Was vorab wichtig ist.</h2></div><Accordion items={service.faqs}/></div></section>
  <section className="section"><div className="container"><span className="eyebrow">Weitere Leistungen</span><div className="services-grid">{related.map(item=><Link className="service-card" key={item.slug} href={`/leistungen/${item.slug}`}><span className="service-no">{item.number}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="service-link">Ansehen <ArrowRight size={18}/></span></Link>)}</div></div></section>
  <section className="section"><div className="container panel" style={{padding:'clamp(2rem,7vw,6rem)'}}><h2 className="display">Projektumfang gemeinsam klären.</h2><p className="lead">Senden Sie uns die wichtigsten Angaben – kostenfrei und unverbindlich.</p><Button href="/angebot">Jetzt Angebot anfragen</Button></div></section></>}
