"use client";
import { useState } from "react";
import { Check, ChevronLeft, ChevronRight } from "lucide-react";
import { services } from "@/content/services";
import { FileUploader, type UploadedFile } from "@/components/forms/FileUploader";

type Quote={customerType:string;service:string;address:string;postalCode:string;city:string;objectType:string;timeframe:string;description:string;firstName:string;lastName:string;company:string;email:string;phone:string;contactMethod:string;uploadedFiles:UploadedFile[];consent:boolean};
const initial:Quote={customerType:"",service:"",address:"",postalCode:"",city:"",objectType:"",timeframe:"",description:"",firstName:"",lastName:"",company:"",email:"",phone:"",contactMethod:"Telefon",uploadedFiles:[],consent:false};
const names=["Kundentyp","Leistungsart","Projektangaben","Kundendaten","Zusammenfassung"];
export function QuoteConfigurator(){const [step,setStep]=useState(0);const [data,setData]=useState(initial);const [status,setStatus]=useState<"idle"|"loading"|"success"|"error">("idle");const [reference,setReference]=useState("");const update=(key:keyof Quote,value:string|boolean)=>setData(current=>({...current,[key]:value}));const valid=[!!data.customerType,!!data.service,!!data.address&&!!data.city&&!!data.description,!!data.firstName&&!!data.lastName&&/\S+@\S+/.test(data.email)&&data.phone.length>=6&&data.consent,true][step];async function submit(){setStatus("loading");try{const response=await fetch("/api/quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error();setReference(result.reference);setStatus("success")}catch{setStatus("error")}}if(status==="success")return <div className="form-card" role="status"><Check className="red" size={40}/><h2>Vielen Dank für Ihre Anfrage.</h2><p className="lead">Ihre Angaben wurden erfolgreich übermittelt. DG Team prüft Ihr Projekt und meldet sich zeitnah bei Ihnen.</p><p className="tag">Referenz: {reference}</p></div>;return <div className="form-card"><div className="quote-progress" aria-label={`Schritt ${step+1} von 5: ${names[step]}`}>{names.map((name,index)=><span className={index<=step?"active":""} key={name}/>)}</div><span className="service-no">SCHRITT {step+1} / 5 · {names[step]}</span>
  {step===0&&<div><h2>Sind Sie Privat- oder Gewerbekunde?</h2><div className="choice-grid">{["Privatkunde","Gewerbekunde"].map(option=><button className={`choice ${data.customerType===option?"selected":""}`} onClick={()=>update("customerType",option)} key={option} aria-pressed={data.customerType===option}>{option}{data.customerType===option&&<Check size={18}/>}</button>)}</div></div>}
  {step===1&&<div><h2>Welche Leistung benötigen Sie?</h2><div className="choice-grid">{[...services.map(s=>s.title),"Noch unsicher"].map(option=><button className={`choice ${data.service===option?"selected":""}`} onClick={()=>update("service",option)} key={option} aria-pressed={data.service===option}>{option}</button>)}</div>{/Saubere|optische/i.test(data.service)&&<p className="notice">Diese Leistung wird grundsätzlich in Verbindung mit einer Hauptleistung angeboten. Bitte nennen Sie die gewünschte Hauptleistung in der Projektbeschreibung.</p>}</div>}
  {step===2&&<div><h2>Beschreiben Sie das Projekt.</h2><div className="form-grid"><Field label="Objektadresse" value={data.address} onChange={v=>update("address",v)}/><Field label="Postleitzahl" value={data.postalCode} onChange={v=>update("postalCode",v)}/><Field label="Ort" value={data.city} onChange={v=>update("city",v)}/><Field label="Objektart" value={data.objectType} onChange={v=>update("objectType",v)}/><Field label="Gewünschter Zeitraum" value={data.timeframe} onChange={v=>update("timeframe",v)}/><label className="field full"><span>Projektbeschreibung *</span><textarea value={data.description} onChange={event=>update("description",event.target.value)} placeholder="Umfang, Menge, Zugänglichkeit, Etage, Aufzug, Parkmöglichkeit und besondere Materialien …"/></label><FileUploader files={data.uploadedFiles} onChange={value=>setData(current=>({...current,uploadedFiles:value}))}/></div></div>}
  {step===3&&<div><h2>Wie dürfen wir Sie erreichen?</h2><div className="form-grid"><Field label="Vorname" value={data.firstName} onChange={v=>update("firstName",v)}/><Field label="Nachname" value={data.lastName} onChange={v=>update("lastName",v)}/><Field label="Firma (optional)" value={data.company} onChange={v=>update("company",v)}/><Field label="E-Mail" type="email" value={data.email} onChange={v=>update("email",v)}/><Field label="Telefon" type="tel" value={data.phone} onChange={v=>update("phone",v)}/><label className="field"><span>Bevorzugter Kontakt</span><select value={data.contactMethod} onChange={event=>update("contactMethod",event.target.value)}>{["Telefon","WhatsApp","E-Mail"].map(option=><option key={option}>{option}</option>)}</select></label><label className="checkbox field full"><input type="checkbox" checked={data.consent} onChange={event=>update("consent",event.target.checked)}/><span>Ich stimme der Verarbeitung meiner Angaben zur Bearbeitung der Anfrage zu. *</span></label></div></div>}
  {step===4&&<div><h2>Angaben prüfen</h2><div className="audience-list">{[["Kundentyp",data.customerType],["Leistung",data.service],["Objekt",`${data.objectType} · ${data.address}, ${data.postalCode} ${data.city}`],["Zeitraum",data.timeframe],["Projektumfang",data.description],["Dateien",data.uploadedFiles.map(file=>file.name).join(", ")||"Keine"],["Kontakt",`${data.firstName} ${data.lastName} · ${data.email} · ${data.phone}`]].map(([label,value])=><div className="audience" key={label}><strong>{label}</strong><p>{value||"–"}</p></div>)}</div><p className="lead" style={{fontSize:'.82rem'}}>Die Anfrage ist kostenfrei und unverbindlich. Nach Prüfung Ihrer Angaben meldet sich DG Team zeitnah bei Ihnen.</p></div>}
  {status==="error"&&<div className="form-status error" role="alert">Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder rufen Sie uns an.</div>}
  <div className="form-nav"><button className="button button-secondary" onClick={()=>setStep(value=>Math.max(0,value-1))} disabled={step===0}><ChevronLeft size={18}/> Zurück</button>{step<4?<button className="button button-primary" onClick={()=>setStep(value=>value+1)} disabled={!valid}>Weiter <ChevronRight size={18}/></button>:<button className="button button-primary" onClick={submit} disabled={status==="loading"}>{status==="loading"?"Anfrage wird gesendet …":"Unverbindliche Anfrage senden"}</button>}</div>
  </div>}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="field"><span>{label} *</span><input type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
